import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google"; 
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";



export const metadata = {
  title: "EduAI",
  description: "Generated by create next app",
};
const outfit = Outfit({subsets:['latin']});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
       <Provider>
        {children}
        </Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
